app.controller("contentController",function($scope,contentService){
	$scope.contentList=[];
	$scope.findByCategoryId=function(categoryId){
		contentService.findByCategoryId(categoryId).success(
				function(response){
					$scope.contentList[categoryId]=response;
				}
		);
	}
	$scope.search=function(){
		location.href="http://127.0.0.1:9104/search.html#?keywords="+$scope.keywords;
	}
});