//定义控制器
	app.controller("brandController",function($scope,$controller,brandService){
		//继承
		$controller("baseController",{$scope:$scope});
		
		$scope.findAll=function(){
			brandService.findAll().success(
				function(response){
					$scope.list=response;
				}		
			);
		}
		//分页
		$scope.findPage=function(page,size){
			brandService.findPage(page,size).success(
					function(response){
						$scope.list=response.rows;
						$scope.paginationConf.totalItems=response.total;
					}
			);
		}
		//保存
		$scope.save=function(){
			var Object=null;
			if($scope.entity.id!=null){
				Object=brandService.update($scope.entity);
			}else{
				Object=brandService.add($scope.entity);
			}
			Object.success(
					function(response){
						if(response.success){
							$scope.reloadList();
						}else{
							alert(response.message);
						}
					}
					);
		}
		//修改
		$scope.findOne=function(id){
			brandService.findOne(id).success(
				function(response){
					$scope.entity=response;
				}		
			);
		} 
		
		//删除
		$scope.dele=function(){
			brandService.dele($scope.selectIds).success(
					function(response){
						$scope.reloadList();
					}		
				);
		}
		//搜索
		$scope.searchEntity={};
		$scope.search=function(page,size){
			brandService.search(page,size,$scope.searchEntity).success(
					function(response){
						$scope.list=response.rows;
						$scope.paginationConf.totalItems=response.total;
					}
					);
		}
		

		
	})